### ISSUE TITLE
Connection example fails with "connection with UseOldRequestStyle() is required"

### ISSUE THREAD

**Issue by superchris** [choria-io/asyncjobs#113]
Copy pasting the example code from your website:

```go
nc, err := nats.Connect("localhost:4222")
panicIfErr(err)

client, err := asyncjobs.NewClient(asyncjobs.NatsConn(nc))
panicIfErr(err)
```

fails with 
```
panic: connection with UseOldRequestStyle() is required
```

**Comment by superchris** [comment]
Also, for fun I tried:

```go
nc, err := nats.Connect(nats.DefaultURL, nats.UseOldRequestStyle())
```

This caused a different error:
```
panic: nats: no responders available for request
```

**Comment by ripienaar** [comment]
> ```
> panic: nats: no responders available for request
> ```


This error is from nats.Connect? Or the call to NewClient()? If from NewClient() then probably it means JetStream is not enabled on your NATS Server

**Comment by superchris** [comment]
Yup, that was it. I was new to NATs and didn't realize what I needed to do start Jetstream

**Comment by ripienaar** [comment]
Cool. Glad you got sorted out!
