### ISSUE TITLE
How to pass username and password to ajc

### ISSUE THREAD

**Issue by superchris** [choria-io/asyncjobs#114]
When starting my nats jetstream server in dev mode, I see the username and password printed to the console. I can use these credentials and successfully connect in go, but when I start ajc I get:

```
ajc runtime error: nats: Authorization Violation
```

Presumably this means I need to pass this into ajc somehow, but see no docs about how to do so.

**Comment by ripienaar** [comment]
Using the nats command line tool create a context that configured access - nats has many ways of authenticating so this is a good way to support them all


https://github.com/nats-io/natscli#configuration-contexts

if you call the context AJC the ajc command will default to that.

**Comment by superchris** [comment]
Previously I had been running with:

```
nats server run --jetstream AJC
```

I had better luck by running:
```
nats-server -c nats.conf
```

with the following in nats.conf:
```
jetstream: enabled
accounts: {
  $SYS: {
    users: [{user: sys, password: pass}]
  }
}
```

TBH, I have no clue what I am doing with NATS and jetstream yet, but this at least got me unstuck. Hopefully it will help others.
