### ISSUE TITLE
ajc tasks cron scheduler is not a thing?

### ISSUE THREAD

**Issue by superchris** [choria-io/asyncjobs#115]
I'm trying to follow the docs for scheduled tasks. It appears that you create scheduled tasks through Golang, but then a separate process must be running for said tasks to be executed. Please correct me if this is wrong. According to the docs, the process to run is:

```
ajc task cron scheduler $(hostname -f) --monitor 8080
```

This does appear to be something ajc knows anything about, instead I just get a list of valid commands. This list shows that there is a `tasks` command but no mention of a `cron` subcommand for it.

**Comment by ripienaar** [comment]
Yeah, JetStream on its own has no kind of scheduled behavior.  So I store the schedule definitions in JetStream but something gotte run that schedule and create tasks as needed.

You can run multiple cron schedulars they will fail over between them etc.

``
[rip@ryzo]% ajc task cron scheduler
ajc runtime error: required argument 'name' not provided

usage: ajc tasks cron scheduler [<flags>] <name>

Runs the Scheduled Task Scheduler

Args:
  <name>  A unique name for this scheduler, used for leader election ($AJC_SCHEDULER_NAME)

Flags:
  --monitor=AJC_MONITOR  Runs monitoring on the given port

Pass --help to see global flags applicable to this command.

```

I run it like:

```
/usr/bin/ajc task cron scheduler ${HOSTNAME} --monitor 8080
```

**Comment by superchris** [comment]
I'm thinking I must have different version of ajc from you somehow. This what i get:

```
superchris@Chriss-MacBook-Pro airia-api-go % ajc task cron scheduler 
usage: ajc [<flags>] <command> [<args> ...]

Choria Asynchronous Jobs

Flags:
  -h, --help          Show context-sensitive help (also try --help-long and --help-man).
      --version       Show application version.
      --context=NAME  NATS Context to use for connecting to JetStream
      --debug         Enable debug level logging

Commands:
  help [<command>...]
  info
  tasks
    add [<flags>] <type> <payload>
    retry [<flags>] <id>
    view [<flags>] <id>
    delete [<flags>] <id>
    list [<limit>]
    purge [<flags>]
    initialize [<flags>]
    configure <retention>
    watch [<flags>]
    process [<flags>] <type> <queue> <concurrency> [<command>]
  queues
    new [<flags>] <queue>
    list
    delete [<flags>] <queue>
    purge [<flags>] <queue>
    info <queue>
    configure [<flags>] <queue>
  package [<flags>]
    docker
```

**Comment by ripienaar** [comment]
yeah that's quite old. What does --version say? I am on 0.1.2

**Comment by superchris** [comment]
Yup that was it.

**Comment by ripienaar** [comment]
ah, bummer, yeah that should be `@latest` sorry, you can send a docs PR if you wish

**Comment by gedw99** [comment]
@ripienaar 
Ironically this could be useful as the schedular ?

they have a nice schedular but no runner :) 

https://github.com/reugn/go-quartz/issues/45

**Comment by ripienaar** [comment]
Quarts is nice yeah :)
