### ISSUE TITLE
failed to run a docker example

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#72]
Hello

I've been following [this](https://github.com/choria-io/asyncjobs/wiki/Running-in-Docker). 
I was able to build an image, but I'm getting a permissions error trying to run the newly generated container.

```bash
docker run -it -v $PWD/nats:/handler/config/nats -p 8086:8080 --rm xxxxx/asynq:test       
INFO[08:26:33] Choria Async Jobs Handler Service git.example.com/example build settings                                                                       
INFO[08:26:33] NATS Context: AJC                                                                                                                              
INFO[08:26:33] Work Queue: SDK                                                                                                                                
INFO[08:26:33] Concurrency: 12                                                                                                                                
INFO[08:26:33] Retry Policy: 1m                                                                                                                               
INFO[08:26:33] Discard State: completed                                                                                                                       
INFO[08:26:33] Prometheus Port: 8080                                
Choria Async Jobs Handler Failed: open /handler/config/nats/context/AJC.json: permission denied
```
OS: Ubuntu 21.10
Asyncjobs: v0.0.7

**Comment by ripienaar** [comment]
That’s weird - could be due to your shell unmask. See if the files in your shell from the nats directory down are all world readable?

**Comment by drev74** [comment]
Hi @ripienaar 

Yes, I have a locally generated file `$PWD/nats/context/AJ_SDK.json`, which is RW.

Guess, there's a mess with the user permissions in the generated [Dockerfile](https://gist.github.com/drev74/94957d605179923aed7724d8b86c19f5). This is my config [yaml](https://gist.github.com/drev74/b2aadbe725937505b231309df5c806b4)

**Comment by ripienaar** [comment]
Please check the permissions of the directory nats and nats/context and the json file. All must be world readable. 

Please show the files here with ls -l

**Comment by drev74** [comment]
```bash
ls -al nats              
drwx------ 3 bku bku 4,0K апр 26 11:21 ./
drwxrwxr-x 7 bku bku 4,0K апр 26 11:21 ../
drwx------ 2 bku bku 4,0K апр 26 14:03 context/
ls -al nats/context/AJ_SDK.json 
-rw------- 1 bku bku 301 апр 26 14:03 nats/context/AJ_SDK.json
```

**Comment by ripienaar** [comment]
You need to make these files world readable and world executable for the directories. 

When mounted into the container they are mounted as root but the ajc components do not run as root so they need to be able to read the files.

**Comment by drev74** [comment]
Okay, that solved the issue with permissions. Thanks @ripienaar 
But I still can't make it work, not due to the context.

I'm getting the following:
`Choria Async Jobs Handler Failed: unknown context "AJC" `

But If I do `nats context ls`, I'm getting the reply. And I was able to use a `nats reply` tool to create a CLI handler for the `AJC` context.
I can also create tasks for my `AJC` context with : `for i in {1..5}; do ajc task add sdk::api -q PING --context AJC '{.....}'; done`

Any thoughts how to fix this ?

Thanks!

**Comment by drev74** [comment]
I'll open another issue for this. Thanks a lot for your support !
