### ISSUE TITLE
bug: task purge won't clean a queue

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#79]
I have an entry in a queue, whereas a task list claims to be empty

```bash
> ajc queue view PONG                                              
PONG Work Queue:
         Entries: 1 @ 178 B
    Memory Based: false
        Replicas: 1
  Archive Period: forever
  Max Task Tries: 20
    Max Run Time: 1h0m0s
  Max Concurrent: 100
     Max Entries: unlimited
      First Item: 03 May 22 15:11:59 UTC (2m5s)
       Last Item: 03 May 22 15:11:59 UTC (2m5s)

> ajc task ls 
ajc runtime error: no tasks found
```
I assume that purging all tasks should clean all queues as well

Ubuntu 21.10
I'm using AJC v0.0.7

**Comment by ripienaar** [comment]
This can happen when the task store has an expiry that evicts messages quicker than the WQ or similar.  JetStream doesnt notify anyone when that happens - but its fine, the WQ entry will go away during processing its harmless

**Comment by ripienaar** [comment]
And if you just delete a task I cant know what WQ entry to remove from the queues, all I can do is fail to process than WQ entry - its harmless

**Comment by ripienaar** [comment]
Closing, as given how JetStream works, not much I can do about it alas - but the system will self clean
