### ISSUE TITLE
feat: protobuf serialization

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#82]
Hello

Currently, I'm working with a double queue design. Few services pass data thru two queues.
I'm dissatisfied with the impl of `NewTTask`. Internally, it calls `json.Marshal`, which messes the data if I pass already binary pre-encoded input from my service. I need to decode JSON multiple times on each level.

Protobuf pros:
- faster serdes
- higher compression
- lower memory/bandwith footprint
- de-facto standard for CNCF tools (docker, kuber, grafana, etc)

Protobuf cons:
- need to maintain a proto definition files
- complicates a bit release and deployment flow

However, given the whole project goal of providing a simple high performance backplane for microservices, I believe it's worth implementing.

Would you consider moving to proto? I may take a lead in implementataion

**Comment by ripienaar** [comment]
I would definitely not consider moving to protobufs. JSON is a easy lingua franca for many languages and easy to work with from CLI and visual inspection, these properties are important to me.

Is the problem that you want to make the task payload protobufs or the whole thing all over?

**Comment by drev74** [comment]
Well, currently I have smth like this:
```go
// APIRequest - top level API request
type APIRequest struct {
  JobID uuid.UUID  `json:"jobid"`
  Cmd   APICommand `json:"cmd"`
}
```
When I send the above msg as a task, I'm getting the following after decode:
```bash
2022-05-04T21:53:14.069+0300    DEBUG   cmd/main.go:101 PONG adding response: {9977d74d-afba-482a-8076-5ee332aefeae [123 34 110 97 109 101 34 58 34 83 97 110 
100 98 111 120 45 115 105 109 117 108 97 116 111 114 34 44 34 105 100 34 58 34 99 99 52 101 99 51 55 57 45 55 102 52 55 45 52 48 49 102 45 56 99 54 99 45 50 9
7 57 57 51 98 49 51 98 98 50 99 34 44 34 99 114 101 97 116 101 100 34 58 34 34 125]}  
```

So this seems a bit ugly that I need to process binary data on each level. And this is a bit confusing, since my service calls `json.marshal` on its own... Maybe I need to skip internal serialization and solely rely on `asyncjobs`.

This is a design decision for me and that's why I'm trying to understand both the long term strategy for this project and the current impl


PS: Thanks for adding a custom logger. That was a good move

**Comment by ripienaar** [comment]
Yes, if you want to pass a object in there just pass it in, let new task serialize it, on receiving it in your handler you then need to deserialize into your struct.

Since we support handlers as scripts/commands and those could be any language I dont want to go protobuf and then having to deal with distribution proto files everywhere and so forth and so on.

**Comment by drev74** [comment]
Alright, thanks for your comments. Feel free to open more issues so that I could pick smth up and contribute
Luck!

**Comment by ripienaar** [comment]
Working on ordering, relations and workflows atm, unfortunately quite giant tasks and implementation is driven by something i need for a client
