### ISSUE TITLE
docs: how to contribute in wiki

### ISSUE THREAD

**Issue by drev74** [choria-io/asyncjobs#88]
Hello

I'd like to contribute in wiki docs. However, when I fork the project, the wiki is not forked :roll_eyes: . There are few ways to work around that.
Which is your way for wiki contributors ? :thinking:

**Comment by ripienaar** [comment]
GitHub wikis are like fatally flawed imo, they can ether be open to everyone to abuse or no1 but project members can contribute :( really sux. And there's no way for someone else to review what goes into a wiki either.

I am thinking of moving to a github pages based wiki that will remove this need.

So I am not sure how we can do it, if you want to make a new page stick the markdown here, if you have changes you'll have to point them out to me until I can move away from these wiki.

**Comment by drev74** [comment]
How about making a docs directory within this project ? Others may contribute thru PRs into it and you will regularly copy-paste updates to wiki

**Comment by ripienaar** [comment]
Better to use github pages - its a directory with files as you say but it auto publishes with no effort from me.

**Comment by drev74** [comment]
Well, I'm okay with GH pages. But I may need an access to current pages to revise/add/improve. I'll add new pages as well

I started to use AJC in our dev env and happy :smiley: with it so far. Wanna share my experience with others.

So I'm leaving up it to you to make a final decision. Just wanna let you know that docs are important to grow a community and I wanna contribute in that too

**Comment by ripienaar** [comment]
Am aware of the important, hoped GH Wiki would be an improvement but in the end its just not useful, so now need something else.

Will experiment with some options

**Comment by drev74** [comment]
How about building a separate web project? Similar to [this](https://choria.io/docs/about/)

**Comment by ripienaar** [comment]
That's literally what I am suggesting. The docs will just be kept in this directory

**Comment by drev74** [comment]
We internally use [Hugo](https://gohugo.io/) engine to maintain docs. 

A good examples of it are [Tekton](https://tekton.dev/) and [grpc](https://grpc.io/). If you click on Tekton's page "Edit", you'll be forwarded to their [website project](https://github.com/tektoncd/website). How about doing exactly that ? :thinking:

**Comment by ripienaar** [comment]
Yes, the other choria docs are also hugo.

**Comment by ripienaar** [comment]
You can see an example here https://github.com/choria-io/appbuilder see the docs directory and then https://choria-io.github.io/appbuilder/

**Comment by crossworth** [comment]
> It's not done (so not advertised and no links updated and wiki still active) but see https://choria-io.github.io/asyncjobs/
> 
> you can send a PR into `docs/...` folder. I have to work a bit more on the theme its a bit bad atm.

Hello, I have been watching this project for some time, I plan to start using it, but didn't have the time yet. I think this project has a lot of potential, thank you for the great work @ripienaar.

With that said, I would like to share a cool hugo theme that I have found a few months ago:
https://getdoks.org

Maybe is something that can be used, I think it has great defaults.

**Comment by ripienaar** [comment]
Thanks for that and the theme suggestion, I have quite a lot of 'hugo learn' https://choria.io/docs/about/ already and I am trying to keep some kind of cohesion, that said the learn one is a bit abandoned so trying out a maintained version of that here, but as these are small projects if it doesnt go well we can surely try something else!
